### ISSUE TITLE
ENH: Add useful reusable modules and files from Q3

### ISSUE THREAD

**Issue by hjdeheer** [TeamEpochGithub/epochalyst#113]
- Timm
- Custom Kornia
- Custom augmentations

More... but take a look what is reusable!

**Comment by schobbejak** [comment]
Create separate issues for adding modules as each has to be tested and implemented in a general manner.

**Comment by tolgakopar** [comment]
Softmax is too specific and pretty easy to write again. Same for threshold.

**Comment by schobbejak** [comment]
Timm if it can be unit tested and a try except needs to be put around the timm improt
