### ISSUE TITLE
ENH: Add Dataloader args to init of main trainer

### ISSUE THREAD

**Issue by tolgakopar** [TeamEpochGithub/epochalyst#140]
We are not able to pass keyword arguments to the datalaoders within epochalyst (things like pre-fetch factor, num_workers, persistent_workers). We can overwrite the create dataloaders method but other methods like custom predict and pred_after_train instantiate their own dataloaders too. We will need to overwrite all of them to use the arguments. Simply adding dataloader_kwargs to the init of the trainer and apassing the self.dataloader_kwargs to all instantiations will fix this issue.

**Comment by schobbejak** [comment]
Don't forget to add ENH: in front of issue
