### ISSUE TITLE
ENH: Add to_predict as runtime arg

### ISSUE THREAD

**Issue by hjdeheer** [TeamEpochGithub/epochalyst#191]
To_predict currently changes the hash that we do not want. Add this at the start of the custom_train, so that we can set to_predict in the train.yaml as a runtime arg:

`        to_predict = train_args.get("to_predict")
        if to_predict is not None:
            self.to_predict = to_predict
`

**Comment by schobbejak** [comment]
Can also set it to repr=False as it could have an impact on postprocessing blocks, so it would fall under issue #181
