### ISSUE TITLE
CI: Don't run tests on all Python versions every PR

### ISSUE THREAD

**Issue by Jeffrey-Lim** [TeamEpochGithub/epochalyst#202]
Generally, any code that works on Python 3.10 works on 3.11 and 3.12 as well. I think it's sufficient to only run tests on 3.10 for every PR and run monthly tests for 3.11 and 3.12.

**Comment by schobbejak** [comment]
Could also just be merging into a version branch only runs 3.10 and merging into main requires all

**Comment by Jeffrey-Lim** [comment]
> Could also just be merging into a version branch only runs 3.10 and merging into main requires all

Sure, let's do that.
