### ISSUE TITLE
Loosen restrictions on packages in pyproject.toml

### ISSUE THREAD

**Issue by schobbejak** [TeamEpochGithub/epochalyst#52]
- Too strict and too high version for 3.10

**Comment by Jeffrey-Lim** [comment]
The fix you just merged causes more issues. Trying to install `epochalyst` now gives this error:

<img width="408" alt="image" src="https://github.com/TeamEpochGithub/epochalyst/assets/33672881/b5494eea-fe9f-4499-bd9e-3179309043cc">

**Comment by schobbejak** [comment]
Yeah it was just reversed
