### ISSUE TITLE
BUG: Logo is broken on PyPI

### ISSUE THREAD

**Issue by Jeffrey-Lim** [TeamEpochGithub/epochalyst#85]
The Epochalyst logo appears broken on PyPI:

<img width="595" alt="image" src="https://github.com/TeamEpochGithub/epochalyst/assets/33672881/6adc92ca-c490-4750-bf2a-3087373d32ae">

Also, use the SVG version instead so you can put the logic for switching between light & dark mode inside the image file instead of using the GH-specific tags in the README that only work on GH.

**Comment by schobbejak** [comment]
Assign it a milestone when you actually fix it
