### ISSUE TITLE
ENH: Allow paths to be `os.PathLike[str]` instead of just `str`

### ISSUE THREAD

**Issue by Jeffrey-Lim** [TeamEpochGithub/epochalyst#97]
Currently, our code assumes that all paths are `str`s. Since the `pathlib` is usually a better way to handle paths, `os.PathLike` should also be an accepted type. `bytes` is another way to work with strings, so we may want to support that as well. 

This change needs to happen in the following files:

- [ ] `epochalyst/_core/_caching/_cacher.py`
- [ ] `epochalyst/pipeline/model/training/torch_trainer.py`

**Edit**: bytes are too annoying to work with, so just allow `str | os.PathLike[str]`.

**Edit 2**: Just discovered that `os.PathLike[str]` also includes `str`, so don't union that type explicitly.

**Comment by schobbejak** [comment]
- Torch trainer has this fixed in (#157) 
- Cacher can implement this in (#127) since it is being rewritten anyway
